swagger: '2.0'
info:
  version: "0.0.1"
  title: EventPoints API
  description: |
    API FOR EVENTPOINTS
  contact: 
    name: "OSWeekends"
    url: "http://www.osweekends.com"
basePath: "/api/v1"
schemes:
  - http  

#Paths Description
paths:
  /:
    get:
      description: |
        Gets API up and runing message
      produces:
        - application/json
      tags:
        - Ping
      responses:
        200:
          description: API up and running message
          schema:
            type: object
            properties:
              message: 
                type: string
            required:
              - message
  /events:
    get:
      description: |
        Gets all tech events for this week
      produces:
        - application/json
      tags:
        - Events
      responses:
        200:
          description: Events propperly fetched
          schema:
            type: array
            items:
              type: object
              properties:
                abstract: 
                  type: string
                abstract_details: 
                  type: string
                date: 
                  type: string
                location: 
                  type: object
                  properties:
                    lat: 
                      type: number
                    lng:
                      type: number
                    name:
                      type: string
                    notes:
                      type: string
                price: 
                  type: object
                  properties:
                    details: 
                      type: string
                    isFree:
                      type: boolean
                    isTrusted:
                      type: boolean
                source: 
                  type: object
                  properties:
                    event_url: 
                      type: string
                    logo:
                      type: string
                    name:
                      type: string
                    url:
                      type: string
                target_url: 
                  type: string
                title: 
                  type: string
                id: 
                  type: string

        500:
          description: Internal Server Error
  /events/{id}:
    get:
      description: |
        Gets tech event details by Id
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of event to fetch
          required: true
          type: string
      tags:
        - Events
      responses:
        200:
          description: Event propperly fetched
          schema:
            type: object
            properties:
              abstract: 
                type: string
              abstract_details: 
                type: string
              date: 
                type: string
              location: 
                type: object
                properties:
                  lat: 
                    type: number
                  lng:
                    type: number
                  name:
                    type: string
                  notes:
                    type: string
              price: 
                type: object
                properties:
                  details: 
                    type: string
                  isFree:
                    type: boolean
                  isTrusted:
                    type: boolean
              source: 
                type: object
                properties:
                  event_url: 
                    type: string
                  logo:
                    type: string
                  name:
                    type: string
                  url:
                    type: string
              target_url: 
                type: string
              title: 
                type: string
              id: 
                type: string
        404:
          description: Event not found
        500:
          description: Internal Server Error
